export const GET_ALL_ESSENTIALS = "GET_ALL_ESSENTIALS";
export const GET_ALL_ESSENTIALS_SUCCESS = "GET_ALL_ESSENTIALS_SUCCESS";
export const GET_ALL_ESSENTIALS_FAIL = "GET_ALL_ESSENTIALS_FAIL";

export const GET_ALL_CUSTOMERS = "GET_ALL_CUSTOMERS";
export const GET_ALL_CUSTOMERS_SUCCESS = "GET_ALL_CUSTOMERS_SUCCESS";

export const GET_ALL_SUPPLIERS = "GET_ALL_SUPPLIERS";
export const GET_ALL_SUPPLIERS_SUCCESS = "GET_ALL_SUPPLIERS_SUCCESS";

export const ADD_NEW_PERSON = "ADD_NEW_PERSON";
export const ADD_NEW_PERSON_SUCCESS = "ADD_NEW_PERSON_SUCCESS";

export const GET_ALL_PRODUCT_HEAD = "GET_ALL_PRODUCT_HEAD";
export const GET_ALL_PRODUCT_HEAD_SUCCESS = "GET_ALL_PRODUCT_HEAD_SUCCESS";
export const ADD_NEW_PRODUCT_HEAD = "ADD_NEW_PRODUCT_HEAD";
export const ADD_NEW_PRODUCT_HEAD_SUCCESS = "ADD_NEW_PRODUCT_HEAD_SUCCESS";

export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";
export const ADD_NEW_PRODUCT_SUCCESS = "ADD_NEW_PRODUCT_SUCCESS";

export const GET_ALL_ACCOUNT_TYPES = "GET_ALL_ACCOUNT_TYPES";
export const GET_ALL_ACCOUNT_TYPES_SUCCESS = "GET_ALL_ACCOUNT_TYPES_SUCCESS";
export const ADD_NEW_ACCOUNT_TYPE = "ADD_NEW_ACCOUNT_TYPE";
export const ADD_NEW_ACCOUNT_TYPE_SUCCESS = "ADD_NEW_ACCOUNT_TYPE_SUCCESS";

export const GET_ALL_WAREHOUSE = "GET_ALL_WAREHOUSE";
export const GET_ALL_WAREHOUSE_SUCCESS = "GET_ALL_WAREHOUSE_SUCCESS";
export const ADD_NEW_WAREHOUSE = "ADD_NEW_WAREHOUSE";
export const ADD_NEW_WAREHOUSE_SUCCESS = "ADD_NEW_WAREHOUSE_SUCCESS";

export const GET_ALL_EXPENSE_ACCOUNTS = "GET_ALL_EXPENSE_ACCOUNTS";
export const GET_ALL_EXPENSE_ACCOUNTS_SUCCESS =
  "GET_ALL_EXPENSE_ACCOUNTS_SUCCESS";
export const ADD_NEW_EXPENSE_ACCOUNT = "ADD_NEW_EXPENSE_ACCOUNT";
export const ADD_NEW_EXPENSE_ACCOUNT_SUCCESS =
  "ADD_NEW_EXPENSE_ACCOUNT_SUCCESS";

export const GET_ALL_AREAS = "GET_ALL_AREAS";
export const GET_ALL_AREAS_SUCCESS = "GET_ALL_AREAS_SUCCESS";
export const ADD_NEW_AREA = "ADD_NEW_AREA";
export const ADD_NEW_AREA_SUCCESS = "ADD_NEW_AREA_SUCCESS";

export const RESET_ADDED = "RESET_ADDED";

export const ADD_EXPENSE_DETAIL = "ADD_EXPENSE_DETAIL";
export const ADD_EXPENSE_DETAIL_SUCCESS = "ADD_EXPENSE_DETAIL_SUCCESS";

export const SET_ERROR = "SET_ERROR";

export const CANCEL_INVOICE = "CANCEL_INVOICE";
export const CANCEL_INVOICE_SUCCESS = "CANCEL_INVOICE_SUCCESS";
