export const GET_ALL_ESSENTIALS = "GET_ALL_ESSENTIALS";
export const GET_ALL_ESSENTIALS_SUCCESS = "GET_ALL_ESSENTIALS_SUCCESS";

export const GET_ALL_CUSTOMERS = "GET_ALL_CUSTOMERS";
export const GET_ALL_CUSTOMERS_SUCCESS = "GET_ALL_CUSTOMERS_SUCCESS";
export const GET_ALL_CUSTOMERS_FAIL = "GET_ALL_CUSTOMERS_FAIL";

export const GET_ALL_SUPPLIERS = "GET_ALL_SUPPLIERS";
export const GET_ALL_SUPPLIERS_SUCCESS = "GET_ALL_SUPPLIERS_SUCCESS";
export const GET_ALL_SUPPLIERS_FAIL = "GET_ALL_SUPPLIERS_FAIL";

export const GET_ALL_PRODUCT_HEAD = "GET_ALL_PRODUCT_HEAD";
export const GET_ALL_PRODUCT_HEAD_SUCCESS = "GET_ALL_PRODUCT_HEAD_SUCCESS";
export const GET_ALL_PRODUCT_HEAD_FAIL = "GET_ALL_PRODUCT_HEAD_FAIL";

export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_FAIL = "GET_ALL_PRODUCT_FAIL";

export const GET_ALL_ACCOUNT_TYPES = "GET_ALL_ACCOUNT_TYPES";
export const GET_ALL_ACCOUNT_TYPES_SUCCESS = "GET_ALL_ACCOUNT_TYPES_SUCCESS";
export const GET_ALL_ACCOUNT_TYPES_FAIL = "GET_ALL_ACCOUNT_TYPES_FAIL";

export const GET_ALL_WAREHOUSE = "GET_ALL_WAREHOUSE";
export const GET_ALL_WAREHOUSE_SUCCESS = "GET_ALL_WAREHOUSE_SUCCESS";
export const GET_ALL_WAREHOUSE_FAIL = "GET_ALL_WAREHOUSE_FAIL";
