export const GET_DAYBOOK = "GET_DAYBOOK";
export const GET_DAYBOOK_SUCCESS = "GET_DAYBOOK_SUCCESS";
export const GET_DAYBOOK_FAIL = "GET_DAYBOOK_FAIL";

export const ADD_DATA_TO_DAYBOOK = "ADD_DATA_TO_DAYBOOK";
