export const FIELDS = {
  PERSON: 'person',
  DATE: 'date',
  ACCOUNT: 'account_type',
  BOOK_NUM: 'manual_invoice_serial',
  BOOK_TYPE: 'serial_type',
  NATURE: 'nature',
  TRANS_TYPE: 'type',
  ACTION: 'requires_action',
  DRAFT: 'draft',
  DISCOUNT: 'discount',
  PAID: 'paid',
  PAID_AMOUNT: 'paid_amount',
  DETAIL: 'detail',
  BUILTY: 'builty',
  // ----------------TRANS DETAIL ---------------- //
  TRANS_DETAIL: 'transaction_detail',
  ID: 'id',
  PRODUCT: 'product',
  GAZAANA: 'yards_per_piece',
  QTY: 'quantity',
  RATE: 'rate',
  WAREHOUSE: 'warehouse',
};

export const INITIAL = {
  [FIELDS.PERSON]: '',
  [FIELDS.DATE]: '',
  [FIELDS.TRANS_TYPE]: '',
  [FIELDS.ACCOUNT]: '',
  // [FIELDS.BOOK_NUM]: '',
  [FIELDS.BOOK_TYPE]: '',
  [FIELDS.BUILTY]: '',
  [FIELDS.ACTION]: false,
  [FIELDS.DISCOUNT]: '',
  [FIELDS.PAID_AMOUNT]: '',
  [FIELDS.DETAIL]: '',
  [FIELDS.TRANS_DETAIL]: [
    {
      [FIELDS.PRODUCT]: '',
      [FIELDS.GAZAANA]: '',
      [FIELDS.WAREHOUSE]: '',
      [FIELDS.RATE]: '',
      [FIELDS.QTY]: '',
    },
  ],
};
