export const typography = {
  fontFamily: "Poppins",
  htmlFontSize: 16,
  fontSize: 14,
  h1: {
    fontFamily: "Poppins",
    fontWeight: 300,
    fontStretch: "normal",
    fontStyle: "normal",
    letterSpacing: "normal",
  },
  h2: {
    fontFamily: "Poppins",
    fontWeight: 300,
    fontStretch: "normal",
    fontStyle: "normal",
    letterSpacing: "0.01px",
  },
  h3: {
    fontFamily: "Poppins",
    fontWeight: 500,
    fontStretch: "normal",
    fontStyle: "normal",
    letterSpacing: "0.01px",
  },
  h4: {
    fontFamily: "Poppins",
    fontWeight: "bold",
    fontStretch: "normal",
    fontStyle: "normal",
    letterSpacing: "0.01px",
  },
  h5: {
    fontFamily: "Poppins",
    fontWeight: "bold",
    fontStretch: "normal",
    fontStyle: "normal",
    letterSpacing: "0.01px",
    textAlign: "left",
  },
  h6: {
    fontFamily: "Poppins",
    fontWeight: "bold",
    fontStretch: "normal",
    fontStyle: "normal",
    letterSpacing: "normal",
  },
  subtitle1: {
    fontFamily: "Poppins",
    fontWeight: "bold",
    fontStretch: "normal",
    fontStyle: "normal",
    letterSpacing: "0.01px",
    "text-transform": "uppercase",
  },
  subtitle2: {
    fontFamily: "Poppins",
    fontWeight: 500,
    fontStretch: "normal",
    fontStyle: "normal",
    letterSpacing: "0px",
  },
  body1: {
    fontFamily: "Poppins",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    letterSpacing: "0px",
  },
  body2: {
    fontFamily: "Poppins",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    letterSpacing: "0.01px",
  },
  button: {
    fontFamily: "Poppins",
    fontWeight: "bold",
    fontStretch: "normal",
    fontStyle: "normal",
    letterSpacing: "0.01px",
  },
  caption: {
    fontFamily: "Poppins",
    fontWeight: "normal",
    fontStretch: "normal",
    fontStyle: "normal",
    letterSpacing: "normal",
  },
};
