export const GET_SINGLE_TRANSACTION = "GET_SINGLE_TRANSACTION";
export const ADD_TRANSACTION_TO_STORE = "ADD_TRANSACTION_TO_STORE";
export const SET_FETCHED_FALSE = "SET_FETCHED_FALSE";

export const GET_ALL_STOCK = "GET_ALL_STOCK";
export const GET_ALL_STOCK_SUCCESS = "GET_ALL_STOCK_SUCCESS";
export const SET_SHOULD_FETCH = "SET_SHOULD_FETCH";
