export const GET_ALL_FORMULAS = "GET_ALL_FORMULAS";
export const GET_ALL_FORMULAS_SUCCESS = "GET_ALL_FORMULAS_SUCCESS";
export const GET_ALL_FORMULAS_FAIL = "GET_ALL_FORMULAS_FAIL";

export const ADD_NEW_FORMULA = "ADD_NEW_FORMULA";
export const ADD_NEW_FORMULA_SUCCESS = "ADD_NEW_FORMULA_SUCCESS";
export const ADD_NEW_FORMULA_FAIL = "ADD_NEW_FORMULA_FAIL";

export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_FAIL = "GET_ALL_PRODUCT_FAIL";

export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";
export const ADD_NEW_PRODUCT_SUCCESS = "ADD_NEW_PRODUCT_SUCCESS";
export const ADD_NEW_PRODUCT_FAIL = "ADD_NEW_PRODUCT_FAIL";
