export const GET_ALL_DYING = "GET_ALL_DYING";
export const GET_ALL_DYING_SUCCESS = "GET_ALL_DYING_SUCCESS";
export const GET_ALL_DYING_FAIL = "GET_ALL_DYING_FAIL";

export const ADD_NEW_DYING = "ADD_NEW_DYING";
export const ADD_NEW_DYING_SUCCESS = "ADD_NEW_DYING_SUCCESS";
export const ADD_NEW_DYING_FAIL = "ADD_NEW_DYING_FAIL";
